#!/usr/bin/env node
/**
 * Turns a baked region (JSON + PNG planes + peaks) into a TypeScript module
 * with the imagery inlined as data: URIs.
 *
 * Preview builds are published as one self-contained page, so nothing may be
 * fetched at runtime; this is where "one file per plane on disk" becomes "one
 * string in the bundle".
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';

const [, , metaPath, outPath] = process.argv;
if (!metaPath || !outPath) {
  console.error('usage: gen_region.mjs <data/region.json> <src/data/generated-region.ts>');
  process.exit(1);
}

const dir = dirname(metaPath);
const meta = JSON.parse(readFileSync(metaPath, 'utf8'));

const uri = (f) => `data:image/png;base64,${readFileSync(join(dir, f)).toString('base64')}`;

const levels = meta.rings.map((r) => ({
  z: r.z, px0: r.px0, py0: r.py0, w: r.w, h: r.h,
  quant: r.quant, bias: r.bias, res: r.res, halfKm: r.halfKm,
  hi: uri(r.hi), lo: uri(r.lo),
}));

const viewpointsPath = join(dir, `${meta.name}.viewpoints.json`);
const viewpoints = existsSync(viewpointsPath)
  ? JSON.parse(readFileSync(viewpointsPath, 'utf8'))
  : [];

const peaksPath = join(dir, `${meta.name}.peaks.json`);
const peaks = existsSync(peaksPath) ? JSON.parse(readFileSync(peaksPath, 'utf8')) : [];

const region = {
  name: meta.name,
  origin: meta.origin,
  levels,
  viewpoints,
};

const body = `// Generated by tools/gen_region.mjs — do not edit.
import type { BakedRegion } from './baked';
import type { Peak } from '../core/peaks';

export const REGION: BakedRegion = ${JSON.stringify(region)};

export const PEAKS: Peak[] = ${JSON.stringify(peaks)};
`;

writeFileSync(outPath, body);
const mb = (body.length / 1024 / 1024).toFixed(2);
console.error(`${outPath}: ${levels.length} levels, ${peaks.length} peaks, ${mb} MB`);
